

.PHONY:
help:
	@echo "=========================================="
	@echo "make run.synthesis   - Run the synthesis"
	@echo "make clear           - Clear the directory"
	@echo "=========================================="
.PHONY:
run.synthesis:
	vivado -mode batch -source run.tcl

.PHONY:
clear:
	rm -rf output vivado*