//@TODO: Fix it
module INSTRUCTION_MEMORY(
    output data_t o_Instruction,
    input  data_t i_Addr
    );

	parameter HEIGHT = `IM_DEPTH;//Memory height
	parameter FILE = `IM_FILE;

	data_t mem [HEIGHT-1:0];//Memory: Word: 1byte

	/*
		The instruction memory is initialized with the hexadecimal code generated by the assembler.
	It's used one C code (Mount.c) to generate this initilization.
	*/
	initial begin
		$readmemh(FILE, mem);//Initialize Memory
	end
	
	//assign o_Instruction = {mem[i_Addr], mem[(i_Addr)+1], mem[(i_Addr)+2], mem[(i_Addr)+3]};//One instruction has 32 bits
	assign o_Instruction = mem[(i_Addr>>2)];//One instruction has 32 bits


endmodule
